# Generated by Django 5.2.4 on 2025-07-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_delete_dsacontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='project_code',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(default='Unnamed Student', max_length=100),
        ),
    ]
