# Generated by Django 5.2.4 on 2025-07-11 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_dsaquestion_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('constraints', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(default='CSE', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='webapp.question'),
        ),
        migrations.DeleteModel(
            name='DSAQuestion',
        ),
    ]
