# Generated by Django 5.2.4 on 2025-07-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_contest_contestquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='start_time',
        ),
    ]
