# Generated by Django 5.2.4 on 2025-07-15 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_question_constraints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0.0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.contest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_testcases', models.IntegerField(default=0)),
                ('total_testcases', models.IntegerField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('contest_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.contestquestion')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='webapp.contestparticipation')),
            ],
        ),
    ]
