# Generated by Django 5.2.4 on 2025-07-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_contestparticipation_participationquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='college_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='project_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
