# Generated by Django 5.2.4 on 2025-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_studentprofile_college_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='leetcode_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='leetcode_score',
            field=models.IntegerField(default=0),
        ),
    ]
