# Generated by Django 5.2.4 on 2025-07-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_studentprofile_leetcode_profile_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='leetcode_easy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='leetcode_hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='leetcode_medium',
            field=models.IntegerField(default=0),
        ),
    ]
