# Generated by Django 5.2.4 on 2025-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_studentprofile_leetcode_easy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
