# Generated by Django 5.2.4 on 2025-07-17 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_studentprofile_codechef_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
