# Generated by Django 5.2.4 on 2025-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_studentprofile_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
