# Generated by Django 5.2.4 on 2025-07-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_question_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='description',
        ),
        migrations.AddField(
            model_name='contest',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Basic', max_length=100),
        ),
    ]
