# Generated by Django 5.2.4 on 2025-07-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_remove_contest_description_contest_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='level',
            new_name='category',
        ),
    ]
